{% set version = "0.6.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggiraph
  version: {{ version|replace("-", "_") }}

source:
  fn: ggiraph_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggiraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggiraph/ggiraph_{{ version }}.tar.gz
  sha256: 7babed10b34ab47872b20700131254ec60906e13cd5a87114a618a23040b9fe9

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-htmltools
    - r-htmlwidgets >=0.6
    - r-rvg >=0.1.1
    - r-xml2 >=1.0.0
  run:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-htmltools
    - r-htmlwidgets >=0.6
    - r-rvg >=0.1.1
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('ggiraph')"           # [not win]
    - "\"%R%\" -e \"library('ggiraph')\""  # [win]

about:
  home: https://davidgohel.github.io/ggiraph
  license: GPL-3
  summary: Create interactive 'ggplot2' graphics using 'htmlwidgets'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
