{% set version = '0.6.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggiraph
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggiraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggiraph/ggiraph_{{ version }}.tar.gz
  sha256: 7babed10b34ab47872b20700131254ec60906e13cd5a87114a618a23040b9fe9

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-gdtools >=0.1.6
    - r-ggplot2 >=3.0.0
    - r-htmltools
    - r-htmlwidgets >=0.6
    - r-xml2 >=1.0.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.12
    - r-gdtools >=0.1.6
    - r-ggplot2 >=3.0.0
    - r-htmltools
    - r-htmlwidgets >=0.6
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('ggiraph')"           # [not win]
    - "\"%R%\" -e \"library('ggiraph')\""  # [win]

about:
  home: https://davidgohel.github.io/ggiraph
  license: GPL-3
  summary: Create interactive 'ggplot2' graphics using 'htmlwidgets'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggiraph
# Type: Package
# Title: Make 'ggplot2' Graphics Interactive
# Description: Create interactive 'ggplot2' graphics using 'htmlwidgets'.
# Version: 0.6.0
# Authors@R: c( person("David", "Gohel", role = c("aut", "cre"), email = "david.gohel@ardata.fr"), person("Mike", "Bostock", role = c("cph"), comment = "d3.js"),  person("Speros", "Kokenes", role = c("cph"), comment = "d3-lasso"),  person("Eric", "Shull", role = c("cph"), comment = "saveSvgAsPng js library"),  person("Eric", "Book", role = c("ctb"), comment = "hline and vline geoms") )
# License: GPL-3
# Copyright: See file COPYRIGHTS.
# Imports: grid, ggplot2 (>= 3.0.0), htmlwidgets (>= 0.6), stats, xml2 (>= 1.0.0), htmltools, Rcpp (>= 0.12.12), gdtools (>= 0.1.6),
# LinkingTo: Rcpp, gdtools
# Suggests: knitr, testthat, rmarkdown, maps, shiny, sf (>= 0.3-4), dplyr
# VignetteBuilder: knitr
# URL: https://davidgohel.github.io/ggiraph
# BugReports: https://github.com/davidgohel/ggiraph/issues
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2018-11-01 07:45:42 UTC; davidgohel
# Author: David Gohel [aut, cre], Mike Bostock [cph] (d3.js), Speros Kokenes [cph] (d3-lasso), Eric Shull [cph] (saveSvgAsPng js library), Eric Book [ctb] (hline and vline geoms)
# Maintainer: David Gohel <david.gohel@ardata.fr>
# Repository: CRAN
# Date/Publication: 2018-11-01 21:50:03 UTC
